const ILLUST = [
    {
        id: 1,
        tag: ["9Lana", "2D", "BALALAIKA"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GHBBZuObwAEiiDD?format=jpg&name=4096x4096",
        image: "",
        description: "BALALAIKA: https://youtu.be/S2Xu6_XWy4M?si=kI-B_kIIszn_AuLl",
    },
    {
        id: 2,
        tag: ["9Lana", "2D", "CHINCHIRO-RHYTHM"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GakRwN5awAAwhwP?format=jpg&name=4096x4096",
        image: "",
        description: "CHINCHIRO-RHYTHM: https://youtu.be/RqK3bGxeH98?si=--OZ-8FIJU-wO2Pn",
    },
    {
        id: 3,
        tag: ["9Lana", "2D", "1st anniversary"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/Go490jlbAAA6GgF?format=jpg&name=large",
        image: "",
        description: "",
    },
    {
        id: 4,
        tag: ["9Lana", "2D", "Youtube Music Weekend", "Key visual"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzbYglWasAAaKNY?format=jpg&name=large",
        image: "",
        description: "",
    },
    {
        id: 5,
        tag: ["9Lana", "2D", "BALALAIKA Acoustic ver"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GakRwN5awAAwhwP?format=jpg&name=4096x4096",
        image: "",
        description: "BALALAIKA Acoustic ver: https://youtu.be/SxyEC5tbo9o?si=GtM2oIa_Uc3amxPk",
    },
    {
        id: 6,
        tag: ["9Lana", "2D", "NINE TAILS"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzwC1ESaQAAVm6o?format=jpg&name=4096x4096",
        image: "",
        description: "NINE TAILS: https://youtu.be/l70B7oRYKoo?si=wOdljwZoKkFIBhbZ",
    },
    {
        id: 7,
        tag: ["9Lana", "2D", "NINE TAILS"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzwC1EUagAAMO35?format=jpg&name=4096x4096",
        image: "",
        description: "NINE TAILS: https://youtu.be/l70B7oRYKoo?si=wOdljwZoKkFIBhbZ",
    },
    {
        id: 8,
        tag: ["9Lana", "2D", "NINE TAILS"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzwhEOuaAAEZfc8?format=jpg&name=4096x4096",
        image: "",
        description: "NINE TAILS: https://youtu.be/l70B7oRYKoo?si=wOdljwZoKkFIBhbZ",
    },
];

export default ILLUST;